### ISSUE TITLE
completed assignment 4b

### ISSUE THREAD

**Issue by Julchen0** [rbtl-fs24/survey-Julchen0#1]
https://forms.gle/oFV1K68VTWCgudNv8
@larnsce

**Comment by larnsce** [comment]
Thank you, @Julchen0. There is a problem with your survey. I end up in a loop that doesn't let me submit it. Please check this and fix it before class on Thursday.

Other suggestions:

- The question "Select which type of waste you recycle" needs to be a checkbox question. Otherwise, I can only select one category. You did this for the next parents related question.

- On "State your reason why you do not recycle". That should only show up if I had selected "I do not recycle" somewhere else. This way it doesn't feel relevant to me.
