### ISSUE TITLE
Julia's Survey

### ISSUE THREAD

**Issue by Julchen0** [rbtl-fs24/survey-Julchen0#2]
Hi guys! Here's the survey to fill out. Please contact me if there are any problems :) 
https://forms.gle/39cPMRHsYQxwSEz2A

@charlottemeyer @sprinz11 @alecumitu @yasemin26 @margauxgo

**Comment by sprinz11** [comment]
Hi, nice questionnaire. :)

In terms of feedback, the only things I could come up with are these:

- The choice of which questions are obligatory to answer and which aren't seems a bit arbitrary. But maybe you just did that as "playing around with the tool".
- Q: "Feedback" - Maybe you could give some suggestions on which topics the feedback could cover. That might help the participant to think of new things.

@larnsce

**Comment by yasemin26** [comment]
Nice survey:)
I have two comments:
-one idea: I think it is a good idea to ask about the parent´s recycling behavior. Maybe it would be interesting to add the question where the parents live, because recycling behavior also varies a lot around the world.
-I was not sure what you wanted to hear as feedback: feedback for the questionnaire or a general comment, maybe you could specify it a little more

@larnsce

**Comment by charlottemeyer** [comment]
Hey! Nice survey :)
My feedback would be:
1. maybe add a question to link your habits and your parents' habits? Something like "hoe did you learn to recycle?"
2. for the question on what do we recycle, you could add the "other" option, as people might recycle even more things than what is on the list

@larnsce

**Comment by margauxgo** [comment]
I've just completed your survey and liked it. However, I do think you could include more questions about the parents' recycling habits. This could help you see if there is influence or not. @larnsce

**Comment by alecumitu** [comment]
Hi! Thank you for your survey. I liked the topic of the influence of parents on the recycling behavior of a person. 
As feedback, I would mention:
- for the questions of the type "if yes, what do they....", I would also add the options of "they do not recycle". I think it is easier to keep track of all the answer possibilities that way, because I didn't answer that question 
- I would have liked an extra section about proposing options to make your parents recycle more
@larnsce
